packages:
  - api
  - web

onlyBuiltDependencies:
  - ffmpeg-static

overrides:
  # Fastify ecosystem - used by echo-api
  fastify@<=5.7.2: '>=5.7.3'
  '@nestjs/platform-fastify@<11.1.10': '>=11.1.11'
  # Axios - used by echo-web
  axios@>=1.0.0 <=1.13.4: '>=1.13.5'
  # Transitive deps of @lhci/cli (devDependency)
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  qs@>=6.7.0 <=6.14.1: '>=6.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  tmp@<=0.2.3: '>=0.2.4'
