#!/usr/bin/env bash

# ============================================
# Generate Production .env File
# ============================================
# This script generates a complete .env file for production
# with secure random passwords and sensible defaults
#
# Usage:
#   ./scripts/generate-production-env.sh
#   ./scripts/generate-production-env.sh --music-path /path/to/music
#
# ============================================

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Default values
MUSIC_PATH="./music"
APP_PORT="4567"

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --music-path)
      MUSIC_PATH="$2"
      shift 2
      ;;
    --port)
      APP_PORT="$2"
      shift 2
      ;;
    --help)
      echo "Usage: $0 [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --music-path PATH    Path to your music library (default: ./music)"
      echo "  --port PORT          Application port (default: 4567)"
      echo "  --help               Show this help message"
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      echo "Use --help for usage information"
      exit 1
      ;;
  esac
done

echo -e "${BLUE}"
echo "═══════════════════════════════════════════════════════"
echo "  🎵 Echo Music Server - Production Setup"
echo "═══════════════════════════════════════════════════════"
echo -e "${NC}"
echo ""

# Check if .env already exists
if [ -f ".env" ]; then
  echo -e "${YELLOW}⚠️  .env file already exists!${NC}"
  echo ""
  read -p "Do you want to OVERWRITE it? (y/N): " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborted. Your existing .env file was not modified."
    exit 0
  fi

  # Create backup
  BACKUP_FILE=".env.backup.$(date +%Y%m%d_%H%M%S)"
  cp .env "$BACKUP_FILE"
  echo -e "${GREEN}✅ Backup created: $BACKUP_FILE${NC}"
  echo ""
fi

# Generate secure random secrets
echo "🔐 Generating secure random passwords..."

if command -v openssl &> /dev/null; then
  # Use OpenSSL (more portable)
  POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -d '\n' | tr -d '/')
  REDIS_PASSWORD=$(openssl rand -base64 32 | tr -d '\n' | tr -d '/')
else
  # Fallback: use /dev/urandom
  POSTGRES_PASSWORD=$(head -c 32 /dev/urandom | base64 | tr -d '\n' | tr -d '/')
  REDIS_PASSWORD=$(head -c 32 /dev/urandom | base64 | tr -d '\n' | tr -d '/')
fi

echo -e "${GREEN}✅ Passwords generated!${NC}"
echo ""

# Create .env file
cat > .env << EOF
# ============================================
# Echo Music Server - Production Configuration
# ============================================
# Auto-generated on: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
#
# ⚠️  IMPORTANT: Keep this file secure!
# Do NOT commit this file to git (.gitignore already configured)
# ============================================

# ============================================
# 🔒 Security (Auto-generated)
# ============================================
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
REDIS_PASSWORD=$REDIS_PASSWORD

# JWT secrets will be auto-generated by Docker on first run
# They are stored in /app/config/secrets.env inside the container
# You don't need to set them here (Jellyfin-style)

# ============================================
# 🎵 Music Library
# ============================================
MUSIC_PATH=$MUSIC_PATH

# ============================================
# 🌐 Application Settings
# ============================================
APP_PORT=$APP_PORT
NODE_ENV=production

# ============================================
# 🌍 CORS (Optional - Auto-detected by default)
# ============================================
# Uncomment and modify if you need specific CORS origins
# CORS_ORIGINS=http://192.168.1.100:4567,https://music.example.com

# ============================================
# 💾 Cache Configuration
# ============================================
ENABLE_CACHE=true
CACHE_ALBUM_TTL=3600
CACHE_TRACK_TTL=3600
CACHE_ARTIST_TTL=7200

# ============================================
# 🔒 Security Settings
# ============================================
BCRYPT_ROUNDS=12
JWT_EXPIRATION=7d
JWT_REFRESH_EXPIRATION=30d

# ============================================
# 📦 Database Settings (Advanced)
# ============================================
POSTGRES_USER=music_admin
POSTGRES_DB=music_server

# ============================================
# 📝 Notes
# ============================================
# - Passwords were auto-generated securely
# - JWT secrets are auto-generated on first run (stored in Docker volume)
# - CORS origins are auto-detected based on your server IPs
# - Music path can be absolute or relative to docker-compose.yml
#
# Quick start:
#   docker compose -f docker-compose.simple.yml up --build -d
#
# View logs:
#   docker compose -f docker-compose.simple.yml logs -f echo-app
#
# For more info, see: PRODUCTION.md
# ============================================
EOF

echo -e "${GREEN}✅ Production .env file created successfully!${NC}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${BLUE}📋 Configuration Summary${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Music Path:    $MUSIC_PATH"
echo "  App Port:      $APP_PORT"
echo "  Environment:   production"
echo ""
echo "  🔒 Security:"
echo "  ├─ PostgreSQL: ✅ Secure password (${#POSTGRES_PASSWORD} chars)"
echo "  ├─ Redis:      ✅ Secure password (${#REDIS_PASSWORD} chars)"
echo "  └─ JWT:        ✅ Auto-generated on first run"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${GREEN}🚀 Next steps:${NC}"
echo ""
echo "  1. Review and customize .env if needed:"
echo "     nano .env"
echo ""
echo "  2. Start the application:"
echo "     docker compose -f docker-compose.simple.yml up --build -d"
echo ""
echo "  3. Access your server:"
echo "     http://localhost:$APP_PORT"
echo ""
echo "  4. View logs:"
echo "     docker compose -f docker-compose.simple.yml logs -f"
echo ""
echo -e "${YELLOW}⚠️  Security reminder:${NC}"
echo "  - Keep .env file secure (already in .gitignore)"
echo "  - Consider setting up HTTPS for internet access"
echo "  - Enable firewall on your server"
echo ""
echo "Done! 🎵"
